# Generated by Django 4.0.3 on 2022-04-01 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atletic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Famale'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('noc', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('medal', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('NA', 'None')], default='NA', max_length=2)),
            ],
        ),
    ]
