# Generated by Django 4.0.3 on 2022-04-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
