# Generated by Django 4.0.3 on 2022-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpics', '0002_alter_athlete_height_alter_athlete_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='medal',
            field=models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('NA', 'None')], default='NA', max_length=10),
        ),
    ]
