# Generated by Django 4.0.3 on 2022-04-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpics', '0003_alter_athlete_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='event',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='games',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sport',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(max_length=256),
        ),
    ]
