# Generated by Django 4.0.3 on 2022-04-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpics', '0004_alter_athlete_city_alter_athlete_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
